---
- hosts: text
  remote_user: root
  serial: 3
  vars:
    local_key_dir: "/root/file/local_login.py"
    remote_script_dir: "/root/ansible/script/python/local_login.py"
    centos6_ius: "/root/ansible/script/file/ius-release-el6.rpm"
    centos6_ius_dest: "/root/file/ius-release-el6.rpm"
    env_dir: "/root/file"
    env_source_dir: /root/python/env
  tasks:
    - name: 创建临时目录
      file:
        path: "/root/file"
        state: directory
        owner: root
        group: root
#-----------------------------Debian部分----------------
    - block:

      - name: 安装python3-venv
        apt:
          name: python3-venv
          state: present
 
      - name: 创建虚拟环境目录
        command: "/usr/bin/python3 -m venv /root/python/env"
        args:
          creates: "/root/python/env/bin/pip"

      - name: 安装python-setuptools
        apt:
          name: python-setuptools
          state: present
          
      - name: Pip安装 pexpect 
        pip:
          name: pexpect
          executable: "/root/python/env/bin/pip3"
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

   
#---------------------------------Centos部分---------------------
    - block:
      - name: 添加python36-devel依赖仓库(Centos7)
        yum_repository:
          name: tbi.EPEL7.repo
          description: home:tbi:EPEL7 (CentOS_7)
          baseurl: http://download.opensuse.org/repositories/home:/tbi:/EPEL7/CentOS_7/
          gpgcheck: no
        when: ansible_distribution_major_version == "7"

      - name: 安装EPEL第三方源(Centos7)
        package:
          name: '{{ item }}'
          state: present
          update_cache: yes
        with_items:
          - epel-release
          - "https://centos7.iuscommunity.org/ius-release.rpm"
        when: ansible_distribution_major_version == "7"
      
      #本地安装依赖源
      - name: 复制依赖源
        copy:
          src: '{{ centos6_ius }}'
          dest: '{{ centos6_ius_dest }}'
          owner: root
          group: root
          mode: 0744

      - name: 安装EPEL第三方源(Centos6)
        package:
          name: '{{ item }}'
          state: present
          update_cache: yes
          validate_certs: no
        with_items:
          - epel-release
          - "{{ centos6_ius_dest }}"
        when: ansible_distribution_major_version == "6"



      - name: python36环境
        package:
          name: '{{ item }}'
          state: present
          update_cache: yes
        with_items:
          - python36u
          - python36u-pip
          - python-setuptools
          
      # - name: 创建虚拟环境
      #   command: "/usr/bin/virtualenv-3.4  /root/python/env"
      #   args:
      #     creates: "/root/python/env"
      - name: 安装virtualenv
        pip:
          name: virtualenv 
          executable: "/usr/bin/pip3.6"

      - name: 创建Borgmatic执行文件链接(Centos6)
        file: 
          path: /bin/python3.6
          src: "/usr/bin/python3.6"
          state: link 
        when: ansible_distribution_major_version == "6"

      - name: 创建虚拟环境
        command: "/usr/bin/virtualenv -p /bin/python3.6 /root/python/env"
        args:
          creates: "/root/python/env"


      - name: Pip安装 pexpect 
        pip:
          name: pexpect
          executable: "/root/python/env/bin/pip"


      when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
    


   
#----------------------公共------------

    - name: 复制脚本到目标主机
      copy:
        src: '{{ remote_script_dir }}'
        dest: '{{ local_key_dir }}'
        owner: root
        group: root
        mode: 0744


    - name: 执行本地密钥安装
      shell: "{{ env_source_dir }}/bin/python {{ local_key_dir }}"