---
- hosts: text
  remote_user: root
  serial: 3
  vars:
    local_key_dir: "/root/file/local_login.py"
    remote_script_dir: "/root/ansible/script/python/local_login.py"
    env_dir: "/root/file"
    env_source_dir: /root/python/env
  tasks:
    - name: 创建临时目录
      file:
        path: "/root/file"
        state: directory
        owner: root
        group: root
#-----------------------------Debian部分----------------
    - block:
      - name: 安装python3-venv
      apt:
        name: python3-venv
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

      - name: 创建虚拟环境目录
        command: "/usr/bin/python3 -m venv /root/python/env"
        args:
          creates: "/root/python/env/bin/pip"
      - name: Pip安装 pexpect 
        pip:
          name: pexpect
          executable: "/root/python/env/bin/pip"
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

   
#---------------------------------Centos部分---------------------
    - block:
      - name: 安装EPEL源
        yum:
          name: epel-release
          state: present
          update_cache: yes
      
      - name: 安装python3.6
        yum:
          name: python36
          state: present

      - name: 安装python36-pip
        yum:
          name: python36-pip
          state: present
  
      - name: 安装 Python-env
        yum:
          name: python36-virtualenv
          state: present
      - name: 创建虚拟环境
        shell: "/usr/bin/virtualenv-3  /root/python/env" 

      - name: Pip安装 pexpect 
        pip:
          name: pexpect
          executable: "/root/python/env/bin/pip"
    when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
    


   
#----------------------公共------------

    - name: 复制脚本到目标主机
      copy:
        src: '{{ remote_script_dir }}'
        dest: '{{ local_key_dir }}'
        owner: root
        group: root
        mode: 0744


    - name: 执行本地密钥安装
      shell: "{{ env_source_dir }}/bin/python {{ local_key_dir }}"